.github/workflows/publish-repos.yml, action-publish-code/action.yml, action-publish-code/publish-code.sh
Change the github action we use to publish repos from the opensource monorepo, to support publishing repos in subdirectories.
With this change we'll be able to publish `typeid/typeid-go` to a `typeid-go` repo. It also makes it possible to specify a custom name that does *not* match the directory name for cases when that's needed (example `dir1/dir2:reponame`).
A follow up PR will use this github action to publish the typeid code.
=> Make it possible to publish opensource repos in subdirectories

typeid/typeid-go/typeid.go
Clarify why the panic case won't trigger in the base32 package
=> Clarify why the panic case won't trigger in the base32 package

action-publish-code/publish-code.sh
The publish script had to bugs:
1. An unnecessary `exit 0` that ended the script early (it was added for debugging and I forgot to remove it)
2. The if statement to handle the case when the `:` is missing from an argument was inverted.
This PR fixes those issues and improves some of the printed messages.
=> Fix bug in publish script, improve messages

go.work, go.work.sum, typeid/typeid-go/typeid.go, typeid/typeid/README.md, typeid/typeid/cli/decode.go, typeid/typeid/cli/encode.go, typeid/typeid/cli/new.go, typeid/typeid/cli/root.go, typeid/typeid/go.mod, typeid/typeid/go.sum, typeid/typeid/main.go
This is the last typeid PR before I start sharing it publicly.
It implements a `typeid` cli with three commands `new`, `encode`, and `decode`. Which let you generate a new typeid, encode a uuid as a typeid, and decode a typeid as a uuid.
In the process add some `FromX` constructors in the `go` version of the library (which brings it to parity with our internal typescript version)
=> Implement typeid cli, and add FromX constructors

.github/workflows/publish-repos.yml
Publish TySON to its own repo (jetpack-io/tyson). I have it as private now, but once I verify the content looks good, I'll make it public.
=> Publish TySON to its own repo

tyson/README.md, tyson/cmd/tyson/cli/root.go, tyson/internal/tsembed/tsembed.go, tyson/msgerror/msgerror.go
=> Add friendly errors to TySON

.github/workflows/monorepo-go.yml
The workflows were deadlocking with each other, remove the concurrency check on tests.
Since "publish" call tests, change the events in which tests trigger by themselves.
=> Fix concurrency with GHA workflows

typeid/typeid/.goreleaser.yaml, tyson/.goreleaser.yaml
We used to use `.Version` in the goreleaser template, but that strips `v` from the version in the cases we want to use that. Switch to `.Tag` which leaves it intact.
=> Use .Tag instead of .Version in goreleaser

typeid/typeid/README.md, tyson/README.md
Add installations instructions to both `typeid` and `tyson` README files.
=> Add installation instructions to README

typeid/typeid-go/typeid.go
Migrated from https://github.com/jetpack-io/typeid-go/pull/1
Compared to the original PR this one tolerates typeids without prefix. It also considers a `[prefix]_[suffix]_[random]` invalid, which I'm assuming it's the right thing to do, specially to support symmetry when going back and forth from strings to typeids.
=> Adds string validation before creating a typeid via FromString

typeid/typeid/README.md
Adding a Ruby implementation of typeid, [typeid-ruby](https://github.com/broothie/typeid-ruby). It's been tested against the provided `valid.yml` and `invalid.yml` files. It does not come with a CLI, not sure if that's a requirement!
=> add github.com/broothie/typeid-ruby to `README.md`

typeid/typeid/spec/README.md
The spec overview incorrectly stated that the type is a suffix.  
The type is a prefix, as stated in the spec chapter "Type prefix".
=> fix(typeid): correct that type is a prefix in spec overview

typeid/typeid/README.md
There is a [spec test class](https://github.com/fxlae/typeid-java/blob/main/src/test/java/de/fxlae/typeid/SpecTest.java) that specifically uses the two files (valid.yml/invalid.yml) for validation against the specification. I marked the entry in the table as "validated" and hope that's ok, if not please just let me know.
=> Add TypeID Java implementation to README

typeid/typeid/README.md
I've begun an implementation for PHP, which you can find at https://github.com/BombenProdukt/typeid. The encoding and decoding implementation is based on https://github.com/jetpack-io/typeid-js. At present, it passes all encodings as per https://github.com/jetpack-io/typeid/blob/main/spec/valid.yml. We are running the tests directly against the `valid.yml` and `invalid.yml` files to promptly detect any failures. ~Tests for the `invalid.yml` file are still missing, but I plan to add them in the coming days as time allows.~
=> Add `BombenProdukt/typeid` for `PHP` to `README.md`

typeid/typeid-go/README.md, typeid/typeid-go/doc.go, typeid/typeid-go/typed/doc.go, typeid/typeid-go/typed/typed.go, typeid/typeid-go/typed/typed_example_test.go, typeid/typeid-go/typeid.go, typeid/typeid-go/typeid_test.go, typeid/typeid/README.md
Cleans up the godocs for the `typeid` go module.
Adds a statically typed version using generics.
=> Statically typed version of TypeIDs using generics

typeid/typeid/README.md
I've implemented TypeID in Zig and successfully tested it against the provided test data.
=> Add Zig implementation to README

typeid/typeid-sql/sql/typeid.sql
Change order of fields in `typeid_generate()` so that it matches the custom type definition. Addresses https://github.com/jetpack-io/typeid-sql/issues/2 as reported by @shellscape
=> [typeid-sql] Change order of fields in typeid_generate()

typeid/typeid/README.md
The test spec is adapted from the [original test in Go](https://github.com/jetpack-io/typeid-go/blob/main/typeid_test.go).
Here's the successful CI: https://github.com/MMZK1526/mmzk-typeid/actions/runs/5490979657/jobs/10007064981
=> Add validation to Haskell implementation of typeid

typeid/typeid-js/README.md, typeid/typeid-js/package.json, typeid/typeid-js/src/typeid.ts, typeid/typeid-js/test/typeid.test.ts, typeid/typeid-sql/README.md
Change the type of the TypeID class to `TypeID<T>` where `T` is the expected prefix.
Update the types of the different methods appropriately. Add an `asType()` method as suggested by @xprnio for cases
when the compiler can't figure out the exact type and we need to do narrowing manually. This is most commonly needed
when parsing a TypeID from a string:
```
TypeID.fromString("prefix_00041061050r3gg28a1c60t3gf").asType("prefix");
```
Add a test for `asType` and update README appropriately
=> [typeid-js] Use generics for TypeID<T> resulting in stronger type checking

typeid/typeid-go/encoding.go, typeid/typeid-go/encoding_test.go, typeid/typeid-go/typed/encoding.go
This implements the `encoding.TextMarshaler` and `encoding.TextUnmarshaler` interfaces as suggested in https://github.com/jetpack-io/typeid-go/issues/4
The PR also adds a test that demonstrates JSON encoding/decoding works correctly.
CC: @Karitham
=> [typeid-go] Implement Text Marshaling

typeid/typeid/README.md
I have a Rust crate which implements TypeID-like behavior for unsigned ints and UUIDs. It is compliant with the TypeID spec when the "typeid" feature is enabled, which is the same as enabling both "uuid" and "uuid-v7" features.
I've included a dedicated crate which pulls the spec files and tests encoding/decoding the values: https://github.com/johnnynotsolucky/strong_id/tree/main/tests/typeid_spec
There is also a github workflow which runs on a 6 hour cron to confirm that the implementation is still valid: https://github.com/johnnynotsolucky/strong_id/blob/main/.github/workflows/typeid_spec.yaml
This crate takes a different approach in that it uses macros to generate TypeIDs so that we can have compile-time validation of prefix rules.
=> Add the strong_id crate as a Rust implementation of TypeID

nixtest/.github/pull_request_template.md, typeid/typeid-go/.github/pull_request_template.md, typeid/typeid-js/.github/pull_request_template.md, typeid/typeid-sql/.github/pull_request_template.md, typeid/typeid/.github/pull_request_template.md, tyson/.github/pull_request_template.md
Add a PR template that automatically warns contributors to send PRs via the opensource monorepo instead.
=> Warn contributors to use OSS monorepo

envsec/internal/envcli/init.go, envsec/internal/jetcloud/client.go, envsec/internal/jetcloud/project.go
Removed extra logging call and passing context in.
`envsec init`
=> [cleanup] Removed logging call, passing context

envsec/internal/envcli/exec.go, envsec/internal/envcli/ls.go
All envsec commands (except `ls` and `exec`) use `strings.ToLower()` when passing `EnvId.EnvName` that means environments like "DEV" and "PROD" becomes "dev" and "prod" in aws ssm.
This creates a bug where you can set a secret with `envsec set key=value` but in `envsec ls` not be able to see that key. This change might be backwards incompatible, but I don't know how envsec at its current state is usable unless someone specifies the environment everytime they `set` and `ls`
- `envsec set testkey=testvalue`
- `envsec ls`
=> [envsec] fix ls envname bug

envsec/internal/auth/cache.go, envsec/internal/auth/jwkscache.go, envsec/internal/auth/user.go
a few implementation decisions:
- The caching is under `auth` package. 
- Cache duration is 1 hour. I check file's last modified. That means a user can manually modify the file to keep the cache going. But because it is client side any approach will have its flaws. So I rather discuss before implementing a solution for it.
- file name is `<domain>.jwks.json`
- readJWKSCache() checks file age as well as reading the cached file. Returns nil in case of cache miss.
- saveJWKSCache() downloads jwks.json and saves the values in a file and returns it. To prevent an extra read cache call after saving the cache.
- devbox run build
- envsec ls
=> [envsec] added caching for jwks public keys

envsec/envsec.go, envsec/parameter_store.go, envsec/ssm_store.go, envsec/util.go
Allow custom var path and namespace. This can be used by launchpad to co continue backward compatibility.
=> [envsec] Allow custom path

envsec/internal/jetcloud/client.go
I want to use a custom endpoint but I'm having some issues with launchpad right now so using default endpoint. We can change this after I fix it or after we move the service to google cloud run.
`envsec ls`
=> [easy][envsec] Switch to prod endpoint

envsec/internal/jetcloud/client.go
If we get an error from the HTTP request, we still try to parse it as JSON,. This change checks the status code, and returns an error if the status code was an error
=> Handle status code errors (easy)

.github/workflows/monorepo-go.yml, envsec/envsec.go, envsec/internal/auth/user.go, envsec/internal/awsfed/awsfed.go, envsec/internal/envcli/auth.go, envsec/internal/filecache/filecache.go, envsec/internal/xdg/xdg.go, envsec/parameter_store.go, envsec/ssm_store.go
This improves performance by making 2 changes:
* Params are looked up by path instead of by tags. Backwards compatibitlity is perseved by doing tag looking for clients that specify custom paths (e.g. launchpad)
* Cache aws credentials. When the cognito/STS exchange happens we get credentials that are good for 60 minutes. We cache them locally and reuse them if they exist and are not expired.
Total improvement was about 1.7s when credentials are cached (2s -> 300ms)
Other changes:
* Added xdg lib as internal (we can opensource so we can share among projects)
* Added simple filecache lib (launchpad uses a similar version. We could open source this as well)
* Used env variables to set auth0 as auth provider
* Benchmarked
When credentials are cached:
* envsec ls is ~500ms
* envsec ls for a …
=> [envsec] Improve performance

envsec/internal/auth/user.go, envsec/internal/envcli/flags.go, envsec/internal/jetcloud/client.go, envsec/internal/jetcloud/project.go, envsec/internal/typeids/typeids.go
* Saves orgID in envsec project config
* Validates that it matches
```
envsec int
cat .jetpack/envsec.json # inspected
envsec set FOO=BAR
envsec ls
vi .jetpack/envsec.json # modified with bad org_id
envsec ls 
```
=> [envsec] Save orgID and validate project belongs to org

envsec/internal/auth/cache.go, envsec/internal/auth/user.go, envsec/internal/awsfed/awsfed.go
This change allows envsec to work end-to-end using auth0. This is ready for dogfooding with devbox if we want.
```
envsec init
envsec set FOO=BAR
envsec ls --show
```
=> [envsec] Use legacy token if needed

typeid/typeid-sql/sql/03_typeid.sql
This PR adds typeid support for columns with nullable ids.
The SQL standard says:
> Every data type includes a special value, called the null value, sometimes denoted by the keyword NULL.
NULL is a valid value for any data type.
```sql
create domain user_id AS typeid check (typeid_check(value, 'user'));
create domain post_id AS typeid check (typeid_check(value, 'post'));
create table users (
"id" user_id not null default typeid_generate('user')
);
create table posts (
"id" post_id not null default typeid_generate('post'),
"user_id" user_id,
FOREIGN KEY(user_id) REFERENCES "users" (id) ON DELETE SET NULL
);
insert into posts ("user_id") values (null);
select typeid_print(user_id) AS user_id from posts
```
=> feat(typeid-sql): add support for nullable columns

envsec/cmd/envsec/main.go, envsec/internal/envcli/root.go, envsec/internal/jetcloud/client.go, envsec/internal/jetcloud/project.go
This helps devbox understand envsec errors. Added a global error flag instead of individual `--format` flags because it is easier to do and not all commands will have `--format`.
`./dist/envsec init --json-errors`
=> [envsec] Add global --json-errors flag

.github/workflows/monorepo-go.yml
Update devbox github action version to v7 for better caching
cicd
=> [CICD] update devbox github action version

.github/workflows/monorepo-go.yml
* Enable devbox cache
* Add golang cache (maybe eventually devbox can handle this as well)
CICD
=> [cicd] Enable devbox cache and add golang cache

envsec/go.mod, envsec/go.sum
This is an unfortunate needed step. When we make changes in pkg, downstream dependencies don't get the newest pkg. This means we need 2 commits. We could automate this, but it would still require an additional commit.
builds
=> [envsec] Bump pkg version to ensure auth location is correct

envsec/internal/envcli/auth.go, envsec/internal/envcli/flags.go, envsec/internal/envcli/init.go
Stacked on https://github.com/jetpack-io/opensource/pull/158
This uses new GetSession interface to show better errors when ID token doesn't exist, is expired, or otherwise invalid.
```
envsec auth logout
envsec init
```
=> [envsec] Better error messages when no valid token

envsec/internal/envcli/auth.go, envsec/internal/envcli/flags.go, envsec/internal/envcli/init.go, pkg/sandbox/auth/auth.go
This will make code more readable and reduce mistakes when using library. An invalid token is not super useful to client.
Updated error messages for new interface.
I still think an error is better (can help with refresh failures, etc) but @loreto you mentioned preferring this. 
Untested.
=> [auth] change GetSession so it returns ok

pkg/sandbox/auth/internal/authflow/authflow.go, pkg/sandbox/auth/internal/callbackserver/callbackserver.go
The auth library currently prints a bunch of debug information to the terminal. Remove that debug info.
=> Remove unnecessary debug logs

envsec/internal/envcli/auth.go, envsec/internal/envcli/flags.go, envsec/internal/envcli/init.go, pkg/sandbox/auth/auth.go, pkg/sandbox/auth/internal/tokenstore/tokenstore.go
* Ensure refresh updates id token, previously it was only updating access token.
* Changed GetSession and a few internal functions to return errors instead of just swallowing it up. 
```
envsec auth logout
envsec auth whoami
envsec auth login
envsec auth whoami
envsec auth refresh
```
=> [envsec] Ensure id token is refreshed

pkg/sandbox/runx/impl/registry/artifact.go, pkg/sandbox/runx/impl/registry/extract.go, pkg/sandbox/runx/impl/registry/registry.go, pkg/sandbox/runx/impl/registry/registry_test.go
Some repos (e.g. https://github.com/mvdan/gofumpt) release files as binaries instead of archives. This expands runx to treat unknown files (that still match the platform and architecture name structure) as binaries. It only does so if it finds a compatible artifact but the type is unknown.
We could additionally test the mime type of the file, but it doesn't seem like binaries use consistent mime types.
`./dist/runx +mvdan/gofumpt gofumpt --help`
=> [runx] Allow non-archived binaries

envsec/pkg/envcli/download.go, envsec/pkg/envcli/exec.go, envsec/pkg/envcli/flags.go, envsec/pkg/envcli/ls.go, envsec/pkg/envcli/rm.go, envsec/pkg/envcli/set.go, envsec/pkg/envcli/upload.go
For launchpad to update we need:
* Allow bootsrapping of a specific envID
* Don't check if flag has changed in the commands themselves.
* Remove `ToLower` Introduced in https://github.com/jetpack-io/opensource/pull/118. This means envsec will be case sensitive. Note that the comments in that PR are not strictly correct, most commands do not do `ToLower` on environment, only `ls` and `exec` did. 
Compiled launchpad with updated version of envsec and tested envsec commands (set, ls, exec, rm)
=> [envsec] Changes to allow launchpad to update

.gitignore, go.work.sum, pkg/go.mod, pkg/go.sum, pkg/sandbox/runx/impl/registry/extract.go
The older version of this extract library has problems. Updating to newer version: `github.com/codeclysm/extract/v3`
see: https://github.com/jetpack-io/pkg/issues/1
`./dist/runx +jetpack-io/envsec envsec --help`
=> update codeclysm dependency

envsec/internal/jetcloud/client.go, envsec/pkg/envcli/auth.go
This change does the following:
* Show better error message if the server returns one. In particular, the server will return instructions with a link to user can activate plan.
* If we fail to get an access token from our STS service, still write id token and refresh toke to store but make it expired. This will ensure we have a valid refresh token and that the next time the user tries to use envsec (presumably after clicking on link and selecting a plan) it will refetch all tokens.
`ENVSEC_API_HOST=http://localhost:8080 ./dist/envsec auth whoami`
=> [envsec] Show good error message when we fail to get access token

devbox.json, envsec/go.mod, envsec/go.sum
Our current devbox scripts use find to run commands inside each of our go modules. However, as written, the scripts return
the exit code of find and not of the executed command. So, if tests fail in one of the go modules, the devbox script still succeeds, because it "found" what we asked it to find.
Rewrite the scripts using `xargs` so that the exit code is correctly propagated.
Broke a test, verified it propagates.
=> [easy][important] Fix build by propagating failures per go module

typeid/typeid-go/bench_test.go, typeid/typeid-go/typeid_test.go
Update benchmarks to measure more functions and make them comparable with benchstat. Also add benchmarks for vanilla UUIDv7 that can be used as a baseline for parsing/encoding functions.
To measure the impact of a change, run the benchmarks for each commit with:
go test -count=10 -bench . > (old|new).txt
Then compare them with benchstat:
go install golang.org/x/perf/cmd/benchstat@latest
benchstat old.txt new.txt
benchstat -filter '-/id:uuid' old.txt new.txt
Initial results:
```
goos: darwin
goarch: arm64
pkg: go.jetpack.io/typeid
│     uuid     │                 untyped                  │                  typed                   │
│    sec/op    │    sec/op      vs base                   │    sec/op      vs base                   │
New-10               404.6n ± 0%     483.4n ± 1% …
```
=> typeid: improve benchmarks

.github/workflows/monorepo-go.yml
TSIA. Note that this right now is creating a bad 'circular dependency'. The go.mod can't be updated, because the most recent code is not published. But the most recent code can't be published, because we only publish if the build is green.
N/A
=> [easy][important] Disable go.mod checks in opensource CI/CD

envsec/go.sum, pkg/go.sum, typeid/typeid-go/bench_test.go, typeid/typeid-go/constructors.go, typeid/typeid-go/subtype.go, typeid/typeid-go/subtype_example_test.go, typeid/typeid-go/subtype_test.go, typeid/typeid-go/typeid.go, typeid/typeid-go/typeid_test.go, typeid/typeid/cli/decode.go, tyson/go.sum
Improvements to TypeID interfaces:
- Add all the standard TypeID methods to the `Subtype` interfaces. When changing code in axiom, noticed that would be useful.
- Make `SubtypePtr` public. Occasionally useful, if one needs to create a 'constructor'-like function outside the `typeid` package.
- Rename `Type()` to `Prefix()`. Been wanting to do this change before. After using typeids, I think `Prefix()` feels more natural and it pairs nicely with the existing `Suffix()`. This change is *not* backwards compatible, but neither was the generics change we did. I'm hoping I can get this in now, and then tag the next release as `v1`.
Ran all tests.
=> Improve TypeID interfaces

devbox.json
Improves the scripts in our root-level devbox.json:
- Each script now prints what directory it's working on
- Linting by default tries to fix issues when it can
- Added a `fmt` script.
Ran locally
=> [opensource] Improve root-level devbox.json

typeid/typeid-sql/example/compound.sql, typeid/typeid-sql/example/text.sql, typeid/typeid-sql/sql/03_typeid.sql, typeid/typeid-sql/sql/04_operator.sql, typeid/typeid-sql/supabase/migrations/04_example.sql, typeid/typeid-sql/supabase/migrations/04_operator.sql, typeid/typeid-sql/supabase/migrations/05_compound_example.sql, typeid/typeid-sql/supabase/migrations/06_text_example.sql, typeid/typeid-sql/supabase/tests/03_typed_text.test.sql, typeid/typeid-sql/supabase/tests/05_operator_test.sql
Improvements to typeid-sql:
- Provide example files for both the text version and the compound version of typeid
- Remove the UUIDv7 check, sometimes people want to store other UUIDs in typeid format
- Rename the equality operator from `=` to `===` (and `!==`). Unfortunately some libraries
give special meaning to `=`, and that breaks functionality like `supabase db diff`
Ran supabase tests
=> Improvements to typeid-sql

envsec/devbox.json, envsec/envsec.go, envsec/pkg/envcli/flags.go
Also adds `devbox run login-dev` as a convenience command to get the dev 
access-token and id-token locally.
NOTE: 
here, the env-var's default value is the prod value. This is consistent with ENVSEC_CLIENT_ID and ENVSEC_ISSUER behavior (but different from what we do in apisvc)
did `devbox run login-dev` and verified the access token
=> [envsec] use ENVSEC_JETPACK_API_ENDPOINT to override

envsec/devbox.json
I had this commented out on my laptop but forgot to commit it prior to landing the PR #205
=> [envsec] comment out ENVSEC_JETPACK_API_ENDPOINT=http://localhost:8080 in login-dev script

pkg/go.mod, pkg/go.sum
This https://github.com/jetpack-io/opensource/pull/187 updated typeid, but it did not follow up with a dependency update. (that means the `pkg` repo was pulling an old version of typeid)
After this is merged, we need to update the pkg dependency as well.
=> [dep] Update typeid in pkg

envsec/jetpack_api_store.go, envsec/pkg/envcli/flags.go, envsec/pkg/envcli/init.go, pkg/jetcloud/client.go, pkg/jetcloud/project.go
This PR lets us use dev-apisvc for all envsec operations in dev-mode, including
CreateProject (which this PR also hooks up)
1. `envsec init` in a new project. Saw `.jetpack.io/dev.project.json` created
2. `envsec ls` and `envsec set` do work
=> [envsec CLI]  use dev-apisvc for all envsec operations in dev-mode, including CreateProject 

envsec/pkg/envcli/flags.go, envsec/pkg/envcli/init.go, pkg/envvar/envvar.go
1. use apisvc by default for prod and dev
2. have a temporary fallback via ENVSEC_USE_AWS_STORE for the previous storage
```
export ENVSEC_PROD=1
envsec init # created .jetpack.io/project.json
envsec set FOO=bar
envsec ls
```
=> [envsec] enable prod-apisvc by default, with fallback to aws via env-var

envsec/.github/workflows/tests.yml
* lint is breaking because of missing file, but we don't really need to lint.
=> [envsec] Fix envsec CICD

envsec/internal/build/build.go, envsec/pkg/envcli/init.go, envsec/pkg/envsec/auth.go, envsec/pkg/envsec/doc.go, envsec/pkg/envsec/envsec.go, envsec/pkg/envsec/init.go, pkg/jetcloud/project.go
Quick and dirty turning envsec into library. Only did `init` for now but if we agree on structure I'll move the rest.
Ideally everything except flags is in there. 
* Creates new `envsec` package
*  Adds struct with `NewProject` function
* Adds `--force` flag to init.
Thoughts or feedback?
`devbox init --force`
=> [RFC] Enpasulate envsec init into lib

typeid/typeid-go/bench_test.go, typeid/typeid-go/constructors.go, typeid/typeid-go/prefix.go, typeid/typeid-go/subtype_test.go, typeid/typeid-go/typeid_test.go, typeid/typeid/cli/encode.go
This change removes the prefix param from `FromUUID` and `FromUUIDBytes`. It follows the philosophy that the correct path should be easy (and the bad path should be less easy).
Previously to convert a UUID you must do:
```golang
// Previously (ugly)
typeid.FromUUID[idType](idType{}.Prefix(), uuid)
// Or potential bug, pass a string
typeid.FromUUID[idType]("typePrefix", uuid)
// After this change
typeid.FromUUID[idType](uuid)
```
Benefits:
* less code in the correct path.
* Much better type checking and less opportunity for miss-use. No way to pass a bad prefix.
Downside:
* AnyIDs are a bit longer and uglier.
* Extra functions
Open to renaming `AnyPrefixFromUUID` to something better. Maybe `FromUUIDWithPrefix` ? or `FromPrefixAndUUID` ?
* builds, tests
=> [RFC] Remove prefix param when possible

pkg/jetcloud/git.go
TSIA
In a follow up, I'll improve project name when not in github repo.
`envsec init` (not in repo)
=> [envsec] Don't require git repo

envsec/envsec.go, envsec/jetpack_api_store.go, envsec/pkg/envcli/flags.go, pkg/api/client.go, pkg/api/secrets.go
This uses the new `apiClient`, which has the benefit of managing the Authorization
header from the token, as well as creating the SecretsService client just once.
I chose to avoid re-defining the SecretsService's methods again. Would prefer
benefitting from the codegen we get and directly using that.
`envsec ls` and `envsec set` work as before
=> [JetpackAPIStore] use apiClient

devbox.json, envsec/internal/flow/init.go, envsec/internal/git/git.go
* `GitSubdirectory` should not break if not in git repo
* Don't give user option to link projects if there are zero projects
* Trim name when validating
=> [envsec] Fix non-git init and don't offer to link if no projects

envsec/internal/flow/init.go
Improves the list styling to make it easier to read.
=> [envsec] Improve project list style

envsec/internal/flow/init.go, envsec/internal/git/git.go
Not worth going to deep into figuring out what is an expected error vs an unexpected. Better to just ignore them.
Tested initializing project in directory without a repo and one with a repo but no remote.
=> [envsec] ignore all git errors

.golangci.yml, envsec/pkg/envsec/auth.go, pkg/auth/auth.go, pkg/auth/internal/tokenstore/io.go, pkg/auth/internal/tokenstore/tokenstore.go, pkg/auth/refreshable.go
Adds multi-session support to auth. 
* Every time a user logs in, we prepend the token to the token slice. We always dedup by subject, so if there's any existing token that matches that subject, we remove it.
* Added `GetSessions` function. `GetSessions` returns refreshable tokens, instead of tokens. This allows the caller to inspect each token to find which one they want without having to refresh all. It also allows them to do useful stuff if only some tokens refresh successfully. 
* Session tokens are saved in a json file that contains a version.
* Logout removes all tokens.
* These changes are fully backwards compatible (which the exception that they will consider current users to be logged out, so they will require a single login on upgrade)
This will support allowing envsec to:
* …
=> [auth] Add multi-session support for auth pkg

.github/workflows/publish-repos.yml
This job seems to update the previous go dependencies. Added a 10s delay to see if it's fixed. If this doesn't work, we can pull a specific hash, but that is more work.
Will test in prod CICD
=> [cicd] Add 10s sleep to insure update dependencies gets latest

envsec/internal/build/build.go, envsec/pkg/envcli/version.go, go.work.sum
TSIA
This will allow for better integration testing with devbox
=> [envsec] Allow setting build env to dev or prod

.github/workflows/monorepo-go.yml, envsec/.github/workflows/release.yml, envsec/.github/workflows/tests.yml
Since our dependencies change quite a bit, using `restore-keys` allows us to leverage previews caches that may not be exact matches.
CICD
=> [CICD] Improve CICD caching

typeid/typeid-js/src/typeid.ts
This PR only changes the type value of `toString()` in typeid-js to allow for the usage of template string types.
```ts
export type UserTypeString = `user_${string}`;
export type UserTypeID = TypeID<'user'>;
private connectedUsers: Record<UserTypeString, User> = {};
const userId = user.id.toString();
connectedUsers[userId] = user;
```
This code will fail type checking if `user.id.toString()` returns a string that doesn't start with `user_`. This adds a bit of type safety, but it also makes the code more readable -- when you look at the `connectedUsers` Record, you know _exactly_ what it's keyed by, not just a generic `string`.
Without this change, you instead have to typecast that `toString()` everywhere:
```
const userId = user.id.toString as UserTypeString;
```
Doable, but ugly.  =)
All …
=> Typed `toString()`.

typeid/typeid/README.md
Closes https://github.com/jetpack-io/typeid/issues/32
* [Repo](https://github.com/TBD54566975/typeid-dart)
* [pub.dev link](https://pub.dev/packages/typeid) (dart / flutter package manager)
* [Tests using vectors provided in spec](https://github.com/TBD54566975/typeid-dart/blob/main/test/typeid_test.dart#L26-L75)
* [Successful build with tests passing](https://github.com/TBD54566975/typeid-dart/actions/runs/8424367913/job/23068076022)
=> Add dart to implementation list

envsec/internal/build/build.go, envsec/pkg/envcli/auth.go, envsec/pkg/envcli/init.go, envsec/pkg/envsec/auth.go, envsec/pkg/envsec/envsec.go, pkg/auth/auth.go, pkg/auth/cmd/auth/cli/login.go, pkg/auth/internal/authflow/authflow.go, pkg/auth/internal/authflow/url.go
TSIA.
Audience is non-standard, but is required and supported by ory.
This is needed to use tokens for identity federation with AWS.
```
envsec auth login
envsec auth whoami --show-tokens
```
=> [auth] Add audience to auth package

pkg/filecache/filecache.go
In response to:
https://github.com/jetpack-io/devbox/blob/main/internal/nix/search.go#L175-L175
=> [filecache] Add IsCacheMiss

typeid/typeid/go.mod, typeid/typeid/go.sum
The typeid CLI wasn't building outside of the workspace because it uses a function that was added after v1.0.0.
=> typeid/cli: fix build

typeid/typeid/README.md, typeid/typeid/spec/README.md, typeid/typeid/spec/invalid.json, typeid/typeid/spec/invalid.yml, typeid/typeid/spec/valid.json, typeid/typeid/spec/valid.yml
- Change spec to allow an underscore _within_ the type prefix
- Add appropriate test cases
- Bump spec version to v0.3.0
- Updated readme to reflect what version of the spec a particular implementation has been validated against.
=> [typeid] Allow '_' in type prefix, update to spec to v0.3

envsec/internal/build/build.go, envsec/pkg/awsfed/awsfed.go, envsec/pkg/envcli/auth.go, envsec/pkg/envsec/init.go, pkg/runx/impl/httpcacher/defaults.go, pkg/runx/impl/registry/registry.go
Update jetpack.io to jetify.com. Will comment individually on backward compatibility.
=> [brand] Update jetpack.io -> jetify

typeid/typeid/README.md
Updating the README to notify that [firenero/typeid](https://github.com/firenero/TypeId) implementation is now compliant with spec v0.3.0
Adjusted test cases to spec v0.3.0
=> README update: C# firenero/typeid compliance with v0.3.0

typeid/typeid/README.md
As suggested, here is the updated README following the adjustments for v0.3
Updated to the 0.3 versions of valid/invalid.yaml
=> TypeId readme: update fxlae/typeid-java to v0.3

typeid/typeid-js/.gitignore, typeid/typeid-js/README.md, typeid/typeid-js/package.json, typeid/typeid-js/src/prefix.ts, typeid/typeid-js/src/unboxed/typeid.ts, typeid/typeid-js/test/invalid.ts, typeid/typeid-js/test/typeid.test.ts, typeid/typeid-js/test/typeid_unboxed.test.ts, typeid/typeid-js/test/valid.ts, typeid/typeid/README.md
Add support for spec 0.3 (underscores in type)
pnpm build
pnpm test
=> [typeid-js] Add support for spec 0.3 (underscores in type)

typeid/typeid/README.md
Updating `typeid-ruby` spec version.
N/A
=> update typeid-ruby spec version

typeid/typeid/README.md
See title.
I pulled the reference tests in my repo and verified my changes made the new tests pass.
=> Update swift-typeid compliance to version 0.3

typeid/typeid/README.md
- https://github.com/sloanelybutsurely/typeid-elixir/pull/30
- published as [0.6.0](https://github.com/sloanelybutsurely/typeid-elixir/releases/tag/0.6.0) ([hex.pm](https://diff.hex.pm/diff/typeid_elixir/0.5.3..0.6.0))
- spec yaml files [were updated](https://github.com/sloanelybutsurely/typeid-elixir/pull/30/files?file-filters%5B%5D=.yml&show-deleted-files=true&show-viewed-files=true) and generated tests re-run
=> Update spec supported by typeid_elixir package

typeid/typeid/README.md
The implementation is based on
[Java @fxlae](https://github.com/fxlae/typeid-java)
It adds more type-safety kotlin features - see
[readme](https://github.com/aleris/typeid-kotlin).
n/a
=> Add link in readme to Kotlin implementation

typeid/typeid-go/testdata/invalid.yml, typeid/typeid/spec/invalid.json, typeid/typeid/spec/invalid.yml
Changes description of the test to match its meaning.
Run `pnpm test` and `go test`.
=> Fix `suffix-hyphens` description in test data invalid.yml

pkg/stackerr/example_test.go, pkg/stackerr/stackerr.go, pkg/stackerr/stackerr_test.go
I wasn't entirely sure which directory this should go under. Let me know if it should be moved.
A more basic version of pkg/errors that offers a `fmt.Errorf` function which can record the filename and line number of where it was called.
Example:
user := "gcurtis"
wrapped := stackerr.Errorf("wrong password")
err := stackerr.Errorf("login %q: %w", user, wrapped)
fmt.Printf("error: %+v\n", err)
// Output:
// error: login "gcurtis": wrong password
// /go/src/handler.go:176 login "gcurtis": wrong password
// /go/src/login.go:14 wrong password
=> stackerr: annotate errors with source file and line number

typeid/typeid-js/README.md, typeid/typeid-js/package.json, typeid/typeid-js/src/typeid.ts, typeid/typeid-js/test/typeid.test.ts
Brings it inline with unboxed version. Makes type-checking much more reliable (because it now throws an error if prefix is wrong). Because the current implementation uses `as T`, if the prefix is not specified, the typechecker type has no relationship to the input data.
Arguably this should have been the default. It requires the same amount of typing because the template type doesn't need to be added:
```ts
const id = TypeID.fromString(stringId, "foo")
// id is of type TypeID<"foo">
```
Unfortunately we can't do this without breaking backward compatibility. 
unit tests
=> [typeid-js] Enforce prefix (optionally)

typeid/typeid-js/src/typeid.ts, typeid/typeid-js/src/unboxed/typeid.ts, typeid/typeid-js/test/typeid.test.ts, typeid/typeid-js/test/typeid_unboxed.test.ts
Throw an error when parsing typeid with empty suffix
Addresses https://github.com/jetify-com/typeid-js/issues/12
pnpm test
=> [typeid-js] Throw error when parsing typeid with empty suffix

typeid/typeid-go/constructors.go, typeid/typeid-go/subtype.go, typeid/typeid-go/testdata/invalid.yml, typeid/typeid-go/typeid.go, typeid/typeid-go/typeid_test.go
- Adds an `IsZero` method that returns true if the typeid has the zero suffix
- Fixes bug where parsing allowed for the empty string as a suffix, and then generated a random suffix in it's place.
Wrote unit tests and ran them.
=> Add IsZero() and fix empty suffix bug

.github/workflows/publish-repos.yml, action-publish-code/action.yml, action-publish-code/publish-code.sh
Assuming the source repo is `org1/repo1`, the targets can now be of these forms:
* `dir1/dir2` -> publishes to `org1/dir2`
* `dir2:repo2` -> publishes to `org1/repo2`
* `dir3:org2/repo3` -> publishes to `org2/repo3`
Ran locally (without actually publishing anything).
Also tested publishing to `jetify-examples/test-repo`:
https://github.com/jetify-com/opensource/actions/runs/10375981931/job/28726924974
=> Generalize publish code action so it can publish to different orgs

typeid/typeid-go/sql.go, typeid/typeid-sql/README.md
Fix typos and clarify usage of different encodings in README
N/A
=> [typeid-sql] Fix typos and clarify usage of different encodings in README

.github/workflows/publish-repos.yml
I'm not 100% sure if this will work the first time, but let's try it. The reason why it might not work is because it'll try to merge whatever is in this repo (in each template) onto the corresponding template repo. It should result in an empty diff and therefore succeed, but again I'm not 100% sure if there's some other check (e.g. history) that might make it fail.
After merging I'll fix-forward if needed.
=> [templates] Publish templates from opensource repo

.github/workflows/publish-repos.yml
The publishing only supports building from devbox or from docker, not nix or buildpacks, so I removed those. I'll add devbox to them afterwards.
CICD
=> [templates] Only publish templates that use devbox

pkg/runx/devbox.json, pkg/runx/impl/registry/artifact.go, pkg/runx/impl/registry/registry_test.go, pkg/runx/impl/types/errors.go
This tweaks the logic in https://github.com/jetify-com/opensource/pull/401 to allow unknown file types if there are no known file types in the list of released artifacts. This is needed because some releases don't have file types at all (e.g. https://github.com/mvdan/gofumpt/releases). We try to return a known archive, otherwise we just return the last artifact that matches the platform (if any)
Note: this is a revert to how the logic behaved before https://github.com/jetify-com/opensource/pull/401 but keeps the artifact name improvements from that PR.
cc: @edorizzardi
* `runx --install mvdan/gofumpt`
* unit tests
=> [runx] Allow unknown file types

.github/workflows/monorepo-go.yml, pkg/auth/internal/tokenstore/io.go, pkg/auth/internal/tokenstore/tokenstore.go, pkg/filecache/filecache.go, pkg/runx/impl/fileutil/fileutil.go, pkg/runx/impl/registry/extract.go, pkg/runx/impl/types/errors.go, templates/hello-go/main.go, typeid/typeid-go/encoding.go, typeid/typeid-go/typeid.go, tyson/api/eval.go, tyson/internal/interpreter/plugin.go, tyson/internal/tsembed/tsembed_test.go
=> [refactor] Run gofumpt, enforcer in CICD

typeid/typeid/README.md
Add a new community implementation of the `v0.3` spec for Zig. 
Note: The old `v0.2` implementation for Zig, listed in the readme, 404s when visited as mentioned in [this issue](https://github.com/jetify-com/typeid/issues/38). I wasn't sure whether or not I should remove it from the readme. Let me know and I'll fix it :) cheers.
Tests implementation: [here](https://github.com/nikoksr/typeid-zig/blob/44494babb3111de3e472f7f16f88f63caf9a2022/src/typeid.zig#L341-L410)
Last successful CI run: [here](https://github.com/nikoksr/typeid-zig/actions/runs/12536940126/job/34960506375)
=> docs(readme): add Zig community implementation

.github/pull_request_template.md
Change pull request template so that it adds a note about the Apache license applying to all contributions to `opensource/`
Wasn't.
=> Add note about license to pull request template

typeid/typeid-js/src/typeid.ts, typeid/typeid-js/src/unboxed/error.ts, typeid/typeid-js/src/unboxed/typeid.ts, typeid/typeid-js/test/typeid.test.ts, typeid/typeid-js/test/typeid_unboxed.test.ts
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0).
By creating this pull request I represent that I have the right to license the
contributions to the project maintainers under the Apache 2 license.
Addresses https://github.com/jetify-com/typeid-js/issues/14
cc: @elieven
devbox run test
=> [typeid-js] Add explicitly defined error types

typeid/typeid-js/package.json, typeid/typeid-js/src/typeid.ts
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0).
By creating this pull request I represent that I have the right to license the
contributions to the project maintainers under the Apache 2 license.
Addresses https://github.com/jetify-com/typeid-js/issues/15. The caller is now able to get the exact type based on typeid prefix, since the return type is conditionally determined by `T extends ""`
cc: @programmarchy
devbox run test
=> [typeid-js] improve type inference for typeid.toString

.github/pull_request_template.md, pkg/try/doc.go, pkg/try/example_test.go, pkg/try/marshal.go, pkg/try/marshal_test.go, pkg/try/try.go, pkg/try/try_test.go
After using `result.Result` for a bit to handle wrapping values and errors, I feel like the name `Result` is too generic and often collides with what the user of the package might be doing. I ran into an example where people were calling this type of wrapper `Try[T]`, and I liked it. This PR renames `Result` to `Try`. I tweaked the names of a few functions as well.
Ran the tests.
Once this is checked in, I will update axiom to use the latest naming.
All community contributions in this pull request are licensed to the project
maintainers under the terms of the
[Apache 2 License](https://www.apache.org/licenses/LICENSE-2.0).
By creating this pull request I represent that I have the right to license the
contributions to the project maintainers under the Apache 2 License as stated in
the …
=> Rename package `result` to `try`

pkg/httpmock/doc.go, pkg/httpmock/examples_test.go, pkg/httpmock/httpmock.go, pkg/httpmock/httpmock_test.go
Improves `httpmock`:
+ Adds a Delay field so users can simulate a delay in the response when needed
+ Improves error messages to provide more context when an expectation fails.
+ Moves examples to it's own file
+ Adds more tests for better coverage.
Wrote and ran unit tests.
=> [httpmock] Support delays and better error messages

pkg/go.mod, pkg/go.sum, pkg/httpmock/examples_test.go, pkg/httpmock/httpmock.go, pkg/httpmock/httpmock_test.go, pkg/httpmock/matcher.go, pkg/httpmock/matcher_test.go, pkg/httpmock/replay.go, pkg/httpmock/replay_test.go, pkg/httpmock/testdata/get_with_header.yaml, pkg/httpmock/testdata/multiple_interactions.yaml, pkg/httpmock/testdata/post_with_body.yaml, pkg/httpmock/testdata/successful_get.yaml, pkg/httpmock/testdata/valid.yaml
Adds a new type of server to `httpmock`: a ReplayServer. This type of server allows you to talk to a real API when first creating the test and then records the interaction for replay later. 
Unit tests.
=> Add ReplayServer

pkg/fileutil/unmarshal.go, pkg/fileutil/unmarshal_test.go
Making these APIs public since they are more generally useful
=> [fileutil] make public UnmarshalReader and FindFiles

.envrc, .gitignore, pkg/httpmock/httpmock.go, pkg/httpmock/httpmock_test.go
This PR reverts a part of #462
The code being reverted would make invalid json received be returned as valid json. No need to do that.
It also makes clients (that are using httpmock library) harder to test. We want the client to be 
able to check for invalid json responses.
go test -v ./pkg/httpmock/...
Also see:  https://github.com/jetify-com/axiom/pull/5879/files#r2061087920
By creating this pull request I represent that I have the right to license the contributions to the project maintainers under the Apache 2 License as stated in the [Community Contribution …
=> [httpmock] revert invalid-json response change from #462

pkg/try/doc.go, pkg/try/example_test.go, pkg/try/try.go, pkg/try/try_test.go
- Rename Wrap -> From for better semantic clarity
- Rename Unwrap -> Get to be more idiomatic
- Rename OrElse -> GetOrElse for consistency with other getters
- Remove Do/Go action methods to simplify the API
- Update all tests and documentation to reflect changes
Updated unit tests, and they pass. 
=> refactor(try): simplify the interface of the Try package. 

.golangci.yml, pkg/optional/doc.go, pkg/optional/optional.go, pkg/optional/optional_concurrency_test.go, pkg/optional/optional_test.go, pkg/optional/primitives.go, pkg/pointer/doc.go, pkg/pointer/example_test.go, pkg/pointer/pointer.go
This PR does two simple changes:
- It makes our linting rules very close to the ones in Axiom
- It moves the code for the optional on-pointer packages from Axiom to open source. This is a straight copy of the code, with no functionality or logic changes
Ran unit tests
=> Move optional and pointer to opensource, update lint rules

.github/workflows/publish-repos.yml
Update our GitHub Action so that we start publishing the AISDK code from this open source mono repo to the new AI repo. 
It wasn't.
=> Start publishing the AI repo

pkg/xdg/xdg.go, pkg/xdg/xdg_test.go
This package adds some helper functions for accessing XDG paths for a user
`devbox run -- go test -v ./pkg/xdg/...`
=> add xdg package

aisdk/ai/provider/openai/internal/codec/decode.go, aisdk/ai/provider/openai/internal/codec/decode_stream.go, aisdk/ai/provider/openai/internal/codec/decode_stream_test.go, aisdk/ai/provider/openai/internal/codec/decode_test.go, aisdk/ai/provider/openai/internal/codec/encode.go, aisdk/ai/provider/openai/llm.go, aisdk/ai/provider/openai/llm_test.go
Implements streaming support in the OpenAI provider.
- Add a Stream method in llm.go that encodes parameters and decodes an OpenAI SSE stream
- Refactor encode.go to clean up metadata handling and reasoning settings
- Introduce decode_stream.go with full event-by-event decoding plus corresponding tests
Unit tests.
=> [AI] Implement streaming in the OpenAI provider

aisdk/ai/aitesting/aitesting.go, aisdk/ai/aitesting/aitesting_test.go, aisdk/ai/api/llm_language_model.go, aisdk/ai/api/llm_prompt.go, aisdk/ai/builder/builder.go, aisdk/ai/builder/builder_test.go, aisdk/ai/builder/convert.go, aisdk/ai/provider/anthropic/codec/decode.go, aisdk/ai/provider/anthropic/codec/decode_test.go, aisdk/ai/provider/anthropic/llm_test.go, aisdk/ai/provider/internal/openrouter/openrouter_chat_language_model.go, aisdk/ai/provider/internal/openrouter/openrouter_chat_language_model_test.go, aisdk/ai/provider/openai/internal/codec/decode.go, aisdk/ai/provider/openai/internal/codec/decode_stream.go, aisdk/ai/provider/openai/internal/codec/decode_stream_test.go, aisdk/ai/provider/openai/internal/codec/decode_test.go, aisdk/ai/provider/openai/internal/codec/encode_tools.go, aisdk/ai/provider/openai/llm.go, aisdk/ai/provider/openai/llm_test.go
Replace separate Response fields (Text, ToolCalls, Sources, Reasoning) with a unified Content []ContentBlock array to maintain output order and simplify API.
- Consolidate all response content into sequential ContentBlock array
- Add a SourceBlock
- Update all provider implementations (OpenAI, Anthropic, OpenRouter)
- Update builders and tests for new unified structure
- Remove deprecated fields like LogProbs from main Response struct
BREAKING CHANGE
Updated tests and ran them.
By creating this pull request I represent that I have the right to license the contributions to the project maintainers under the Apache 2 …
=> [AI] Refactor Response struct to have a single Content field

aisdk/ai/README.md
=> Update AI SDK README

aisdk/ai/ai.go, aisdk/ai/examples/README.md, aisdk/ai/examples/basic/streaming-text/main.go
Adds StreamText and StreamTextStr to the top-level `ai` package. These are the streaming counterparts to GenerateText and GenerateTextStr.
Adds an example showing the streaming case.
Ran the example successfully.
=> [ai] Add StreamText with an example

aisdk/ai/api/llm_call_options.go, aisdk/ai/api/llm_call_options_test.go, aisdk/ai/api/llm_provider_metadata.go, aisdk/ai/api/llm_tool.go, aisdk/ai/provider/anthropic/codec/encode_tools.go, aisdk/ai/provider/anthropic/codec/encode_tools_test.go, aisdk/ai/provider/anthropic/codec/tools.go, aisdk/ai/provider/anthropic/tools.go, aisdk/ai/provider/openai/internal/codec/encode_tools.go, aisdk/ai/provider/openai/internal/codec/encode_tools_test.go, aisdk/ai/provider/openai/internal/codec/tools.go, aisdk/ai/provider/openai/llm_test.go, aisdk/ai/provider/openai/tools.go
This PR makes it possible to marshal and unmarshall CallOptions to/from JSON. In particular, I had to change ProvderDefinedTool from an interface to a concrete type so that it could be appropriately serialized.
Details:
- Add custom JSON unmarshaling for CallOptions to handle polymorphic ToolDefinition interface
- Add JSON unmarshaling for ProviderMetadata
- Implement automatic "type" field inclusion for FunctionTool and ProviderDefinedTool JSON marshaling
- Refactor Anthropic provider to use generic convertArgs helper for flexible tool argument conversion
- Support both struct-based and map[string]any tool arguments
- Add comprehensive tests for JSON marshaling/unmarshaling
Wrote unit test for json serialization, updated existing tests appropriately.
All community contributions in this …
=> Add serialization support for Call Options

aisdk/ai/provider/openai/internal/codec/encode_prompt.go, aisdk/ai/provider/openai/internal/codec/encode_prompt_test.go
Change the computer-use tool to handle text content in addition to image content. Previously, the tool only accepted single image blocks, but now it can process text blocks, mixed content (text + images), and multiple text blocks.
- Relaxed validation to allow multiple content blocks instead of requiring exactly one
- Added support for text-based tool results with proper concatenation
- Enhanced error messages to be more descriptive about content requirements
Added unit tests. 
By creating this pull request I represent that I have the right to license the contributions to the project maintainers under the Apache 2 …
=> Handle text case in computer-use tool

typeid/typeid-sql/README.md, typeid/typeid-sql/package.json, typeid/typeid-sql/sql/03_typeid.sql, typeid/typeid-sql/supabase/tests/03_typed_text.test.sql, typeid/typeid-sql/supabase/tests/03_typeid.test.sql
Implement [TypeID specification 0.3.0](https://github.com/jetify-com/typeid/tree/85d564039674e6f0b972e7b3e3e2bcadd8c176dc/spec#readme) in `typeid-sql`.
> [!NOTE]
> _PLEASE_ tag the repository with the specification and provide a changelog. 🙏 
```sh
yarn install
yarn test
```
=> feat(sql): implement TypeID specification 0.3.0 in typeid-sql

aisdk/ai/provider/mock/mock.go, aisdk/ai/provider/mock/mock_test.go
Adds a `mock` Language Model to the AI SDK that is useful for testing.
Added unit test.
=> Add a mock LanguageModel to the AI SDK

pkg/httpmock/matcher.go, pkg/httpmock/replay.go, pkg/httpmock/replay_test.go, pkg/httpmock/testdata/server_additional_ignored_headers.yaml, pkg/httpmock/testdata/server_no_additional_ignored_headers.yaml
Add a feature to `httpmock` so users can specify additional headers that should be ignored. Realized we need this after the stainless headers caused my etude in axiom to fail.
Wrote unit tests and ran them.
=> [httpmock] Ignore additional headers

pkg/fileutil/unmarshal.go, pkg/go.mod, pkg/try/marshal.go, pkg/try/marshal_test.go, typeid/typeid-go/encoding_test.go, typeid/typeid-go/go.mod, typeid/typeid-go/go.sum, typeid/typeid-go/sql_test.go, typeid/typeid-go/typeid_test.go
Use goccy/go-yaml for yaml parsing instead of gopkg.in/yaml.v3
Ran all unit tests
=> Use goccy/go-yaml for yaml parsing instead of gopkg.in/yaml.v3
