jetify-com/opensource

- .github/workflows/publish-repos.yml
> Start publishing typeid repos

- typeid/typeid-go/README.md
- typeid/typeid/README.md
Improve TypeID README to link to implementations. Made some additional small tweaks as well.
> Improve TypeID README to link to implementations

- tyson/internal/tsembed/tsembed.go
Bump to ES6 (main features we care about like `const` and anonymous functions work)
> Bump to ES6

- .github/workflows/monorepo-go.yml
- typeid/typeid/.github/workflows/release.yml
- typeid/typeid/.goreleaser.yaml
- tyson/.github/workflows/release.yml
- tyson/.goreleaser.yaml
CICD actions to release tyson and typeid using goreleaser.
> Release GHA for tyson and typeid

- typeid/typeid-go/CONTRIBUTING.md
- typeid/typeid-sql/CONTRIBUTING.md
- typeid/typeid/CONTRIBUTING.md
- typeid/typeid/README.md
- tyson/CONTRIBUTING.md
- tyson/README.md
- Add CONTRIBUTING files
- Point Devbox button to landing page
- Improve TySON readme
- Add "Tarpit Law" discussion to TySON
> Improve READMEs and CONTRIBUTING files in opensource repo

- typeid/typeid/README.md
Thank you for validating my implementation Daniel!
> adds validated against spec for @ongteckwu

- typeid/typeid/README.md
Test suite here: https://github.com/conradludgate/type-safe-id/blob/main/tests/spec.rs.
Fuzzing has also been configured and run for a large amount of time (10 minutes).
> update rust type-safe-id compliance

- typeid/typeid/README.md
I am pleased to inform that the validation of the implementation against the provided specifications has been completed successfully.
Once we secure approval for this pull request, my next plan of action involves publishing the library to the nuget.org package source.
> C# implementation validated against spec

- typeid/typeid/README.md
follow up on https://github.com/jetpack-io/typeid/pull/21#issuecomment-1622567164
moved pr here as well as updated to pass against the [new specs](https://github.com/softprops/typeid-java/commit/266bd10d9dbd447a7c8d1edc5e97e221dcf90618)
> add java impl

- typeid/typeid/README.md
https://github.com/jetpack-io/typeid/issues/24
> Adding a Haskell implementation for typeid

- typeid/typeid-go/testdata/invalid.yml
- typeid/typeid-js/test/invalid.ts
- typeid/typeid-js/test/valid.ts
- typeid/typeid/scripts/update_specs.sh
- typeid/typeid/spec/invalid.json
- typeid/typeid/spec/invalid.yml
- Added a script to update all spec-based files after a change to `typeid/typeid/spec/invalid.yml` is made.
- Updated spec files
> Update invalid.yml description

- tyson/README.md
Transferring PR from here:
https://github.com/jetpack-io/tyson/pull/5
as per the request in the PR by @loreto
> Fix typos in readme

- typeid/typeid/README.md
In response to this https://github.com/jetpack-io/typeid/pull/25#issuecomment-1631437351.
> Update date of Swift libs specs validation

- typeid/typeid/README.md
I've also put my implementation last in .NET section to keep it consistent with other items ordering which seems to be by ascending of verification date.
> Add verification date to .NET implementation

- typeid/typeid-go/README.md
I'm currently evaluating this for a project, and I saw that examples in the README don't work out of the box. I did some investigation on my own, and decided to contribute back with a fix.
> Fixed README.md

- envsec/internal/jetcloud/client.go
> [easy][envsec] Don't send org-id (it is in token)

- envsec/internal/auth/cache.go
- envsec/internal/auth/user.go
- envsec/internal/awsfed/awsfed.go
- envsec/internal/envcli/auth.go
Switch envsec auth to auth provider
Untested.
> [envsec] Switch to stytch

- envsec/internal/jetcloud/client.go
> [easy][envsec] Fix envsec-service client

- go.work
- pkg/CODE_OF_CONDUCT.md
- pkg/LICENSE
- pkg/README.md
- pkg/dummy.go
- pkg/go.mod
Create /pkg for common utilities
N/A
> Create /pkg for common utilities

- envsec/internal/envcli/flags.go
- envsec/internal/envcli/root.go
This got a bit broken when we integrated new auth lib
> [envsec] Fix genConfig

- .github/workflows/publish-repos.yml
Start publishing the pkg/ repo
N/A
> Start publishing the pkg/ repo

- envsec/.github/workflows/release.yml
- envsec/.goreleaser.yaml
> [envsec] Add releaser

- envsec/go.mod
- envsec/go.sum
- go.work.sum
> [envsec] Remove go.mod replace

- .github/workflows/monorepo-go.yml
> [cicd] Disable devbox cache

- .github/workflows/monorepo-go.yml
Reverts jetpack-io/opensource#155
> Revert "[cicd] Disable devbox cache"

- envsec/internal/envcli/auth.go
> [envsec] Add show-tokens flag

- envsec/go.mod
- envsec/go.sum
> [envsec] Bump pkg dependency

- envsec/go.mod
- envsec/go.sum
> [envsec] Update pkg dependency

- envsec/internal/envcli/flags.go
- envsec/pkg/awsfed/awsfed.go
title says it
envsec init
envsec ls
envsec set demo=value
all above commands work as expected
> Moved awsfed to pkg/awsfed

- pkg/sandbox/auth/internal/callbackserver/callbackserver.go
Fix race condition in auth library. In the process I changed the hardcoded redirect URL, but I still should send a follow up PR that allows the redirect to be configurable (so that this library is generic and can be used by anyone)
auth cli
> Fix race condition in auth library

- .gitignore
- envsec/internal/jetcloud/client.go
- envsec/internal/jetcloud/token.go
- envsec/pkg/envcli/auth.go
- pkg/sandbox/auth/auth.go
- pkg/sandbox/auth/cmd/auth/cli/login.go
Adds post-login and post-refresh hooks to auth library so we can fetch and replace access token with our a custom short term token.
Untested, but will test using new token endpoint
> [auth] Adds auth hooks to fetch STS access token

- envsec/go.mod
- envsec/go.sum
> [easy] Bump pkg

- envsec/envsec.go
- envsec/go.mod
- envsec/go.sum
- envsec/pkg/envcli/flags.go
also ran `go mod tidy`
`envsec ls` now lists `preview` environment
> [easy][envsec CLI] use preview instead of staging to match Dashboard

- envsec/.goreleaser.yaml
- envsec/devbox.json
- envsec/envsec.go
- envsec/internal/build/build.go
- envsec/jetpack_api_store.go
- envsec/pkg/envcli/auth.go
- envsec/pkg/envcli/root.go
- envsec/pkg/envcli/version.go
* Default issuer, client ID and api host to dev.
* Add ld flags to set correct build values
* Add version command
Compiles
> [envsec] Add build package, default values to dev

- envsec/pkg/envsec/init.go
- pkg/auth/auth.go
This improves ux for envsec and devbox
```
envsec auth logout
envsec init
```
> [easy][envsec] login if needed when doing envsec init

- envsec/pkg/envcli/flags.go
We're accidentally checking wrong config.
> [envsec] fix dev

- .github/workflows/monorepo-go.yml
- devbox.json
> [easy][cicd] Fix bad refactor

- envsec/.github/workflows/release.yml
- envsec/.github/workflows/tests.yml
- typeid/typeid/.github/workflows/release.yml
- tyson/.github/workflows/release.yml
> [cicd] Fix go version in cicd

- envsec/pkg/envcli/download.go
- envsec/pkg/envcli/exec.go
- envsec/pkg/envcli/flags.go
- envsec/pkg/envcli/ls.go
- envsec/pkg/envcli/rm.go
- envsec/pkg/envcli/set.go
- envsec/pkg/envcli/upload.go
- envsec/pkg/envcli/util.go
- envsec/pkg/envsec/auth.go
- envsec/pkg/envsec/delete.go
- envsec/pkg/envsec/envsec.go
- envsec/pkg/envsec/init.go
- envsec/pkg/envsec/list.go
- envsec/pkg/envsec/projects.go
- envsec/pkg/envsec/set.go
- envsec/pkg/envsec/store.go
- envsec/pkg/stores/jetstore/jetstore.go
- envsec/pkg/stores/ssmstore/ssmstore.go
Implements:
* Set, SetMap, SetFromArgs library functions 
* Implements `DeleteAll`
* Clean up logic in `genConfig`
* Moved some output from stdout to stderr.
`ls`, `set`, `rm`, `upload`, `download`
> [envsec] Implement Set,Delete as library functions

- envsec/pkg/envcli/auth.go
- envsec/pkg/envcli/download.go
- envsec/pkg/envcli/flags.go
- envsec/pkg/envcli/info.go
- envsec/pkg/envcli/init.go
- envsec/pkg/envcli/ls.go
- go.work.sum
> [polish] Small helptext edits, for consistency

- typeid/typeid-js/package.json
bump version to 0.5.0
npm publish
> [typeid-js] bump version to 0.5.0

- envsec/internal/build/build.go
- envsec/pkg/envcli/auth.go
- envsec/pkg/envcli/init.go
- envsec/pkg/envsec/auth.go
- envsec/pkg/envsec/envsec.go
- pkg/auth/auth.go
- pkg/auth/cmd/auth/cli/login.go
- pkg/auth/internal/callbackserver/callbackserver.go
- pkg/auth/session/idclaims.go
Updates oauth success url and allows custom. This also fixes bug when using dev auth provider by pointing to correct success url in dev environment.
`envsec auth login`
> [auth] Update success url, allow custom

- .github/workflows/publish-repos.yml
- devbox.json
- envsec/go.mod
- envsec/go.sum
* Update pkg
Trying to fix auto-update action:
* Change action to wait 20s
* Use `main` instead of `latest`
> [deps] Update pkg

- .github/workflows/monorepo-go.yml
- .github/workflows/publish-repos.yml
- envsec/.github/workflows/release.yml
- envsec/.github/workflows/tests.yml
- typeid/typeid/.github/workflows/release.yml
> [cicd] Bump action versions

- typeid/typeid/README.md
Reference to my OCaml implementation.
> feat: reference OCaml implementation

- pkg/api/client.go
- pkg/api/secrets.go
Add token service client
builds
> [easy][api] Add token service client

- go.work.sum
- pkg/api/tokens.go
- pkg/go.mod
- pkg/go.sum
- pkg/ids/ids.go
Forgot to add these. Needed for devbox.
Builds
> [api] Add token service functions

- envsec/go.mod
- envsec/go.sum
> [easy]Update internal deps

- envsec/go.mod
- envsec/go.sum
> ran dx run update-internal-deps

- pkg/go.sum
- typeid/typeid-go/go.sum
> [easy] Update internal dependencies

- .github/workflows/monorepo-go.yml
- .github/workflows/publish-repos.yml
- envsec/.github/workflows/tests.yml
- envsec/.goreleaser.yaml
- envsec/internal/git/git.go
- nixtest/README.md
- nixtest/example/flake.nix
- typeid/typeid-go/README.md
- typeid/typeid-js/package.json
- typeid/typeid-sql/README.md
- typeid/typeid/.goreleaser.yaml
- typeid/typeid/README.md
- tyson/.goreleaser.yaml
> [rename] jetpack-io -> jetify-com

- typeid/typeid-js/package.json
> name and link change for typeid-js

- action-publish-code/README.md
- action-publish-code/action.yml
- envsec/internal/build/build.go
- envsec/pkg/awsfed/awsfed.go
- typeid/typeid/README.md
- tyson/README.md
> Update name and links

- typeid/typeid-sql/devbox.json
- typeid/typeid-sql/devbox.lock
- typeid/typeid-sql/package.json
- typeid/typeid-sql/yarn.lock
> [deps] Update unsafe dependency

- envsec/go.mod
- envsec/go.sum
- pkg/go.mod
- pkg/go.sum
- typeid/typeid-go/README.md
- typeid/typeid-go/bench_test.go
- typeid/typeid-go/constructors.go
- typeid/typeid-go/encoding_test.go
- typeid/typeid-go/go.mod
- typeid/typeid-go/sql_test.go
- typeid/typeid-go/subtype_example_test.go
- typeid/typeid-go/subtype_test.go
- typeid/typeid-go/typeid.go
- typeid/typeid-go/typeid_test.go
- typeid/typeid-go/validate.go
> typeid: go.jetpack.io -> go.jetify.com

- pkg/api/tokens.go
> [easy][api] Rename client function

- devbox.json
- envsec/docs/envsec.md
- envsec/docs/envsec_exec.md
- envsec/pkg/envcli/exec.go
- typeid/typeid-js/devbox.json
- typeid/typeid-sql/devbox.json
> [easy] Company rename

- typeid/typeid-go/constructors.go
- typeid/typeid-go/testdata/invalid.yml
- typeid/typeid-go/testdata/valid.yml
- typeid/typeid-go/validate.go
- typeid/typeid/README.md
- typeid/typeid/spec/README.md
TSIA
Added newest spec tests and they all pass
> [typeid] Add support for spec 0.3 (underscores in type)

- typeid/typeid/README.md
> Update Scala uuid4cats-effect spec version

- typeid/typeid/README.md
Updates Rust `type-safe-id` version specification
https://github.com/conradludgate/type-safe-id/actions/runs/8665674955/job/23764857568
> update rust type-safe-id version

- pkg/api/tokens.go
- pkg/ids/apikey.go
- pkg/ids/ids.go
TSIA This got changed on server, but never got changed here.
> [api] Rename API key type

- typeid/typeid-js/README.md
> [typeid] Update typeid-js README.md

- typeid/typeid/README.md
Added a small section to link to typeid online converter.
Readme change
> added link to online converter

- typeid/typeid-js/README.md
- typeid/typeid-js/package.json
Update version to 1.0.0. Update readme.
N/A
> [typeid-js] update version and readme

- envsec/internal/build/build.go
> Update auth login success url on dev

- api/ts/README.md
- api/ts/devbox.json
- api/ts/examples/create-sandbox/package.json
- api/ts/examples/create-sandbox/pnpm-lock.yaml
* Published dev package
* Updated readme
* Updated example to use published version
`node index.js` in example dir.
> [ts-api] Update readme and example

- api/ts/README.md
- api/ts/eslint.config.mjs
- api/ts/examples/create-sandbox/index.js
- api/ts/examples/create-sandbox/package.json
- api/ts/examples/create-sandbox/pnpm-lock.yaml
- api/ts/package.json
- api/ts/pnpm-lock.yaml
- api/ts/src/client/client.ts
- api/ts/src/client/index.ts
- api/ts/src/index.ts
Improves the typescript API. See example or readme.
`node index.js` in example
> [api] Better ts api

- api/ts/package.json
- api/ts/tsup.config.js
> [api] add tsup config for api ts

- api/ts/README.md
- api/ts/devbox.json
- api/ts/package.json
TSIA
https://www.npmjs.com/package/@jetify/client?activeTab=code
> [ts-api] Publish types, bump version, fmt

- .github/workflows/publish-repos.yml
Before I move everything, I'm just testing that this simple hello-world template in Go gets published (both image and code) properly.
CICD
> [template] Test publishing hello-go template

- typeid/typeid-sql/README.md
Corrects name of PostgreSQL in `README.md`
1-line text change in `README.md`
n/a
> Update typeid-sql README.md

- typeid/typeid-js/package.json
> Upgrade typeid-js to v1.1.0

- .gitignore
- pkg/auth/auth.go
- pkg/auth/cmd/auth/cli/login.go
- pkg/auth/cmd/auth/cli/whoami.go
- pkg/auth/devbox.json
- pkg/auth/devbox.lock
@mohsenari this should help your use case. You can do:
```golang
tok := &session.Token{
Issuer:  "https://accounts.jetify.com",
IDToken: "<id-token>",
Token: oauth2.Token{
AccessToken: "<access-token>",
},
}
// Optional if you don't know the exact expiry you can just get it from the claims
tok.Expiry = tok.IDClaims().Expiry.Time()
err := client.AddSession(tok)
```
Tested with the code above and then used `auth whoami` and inspected the auth json manually.
> [auth] Add whoami and AddSession

- pkg/errors/errors.go
> [RFC] Add Join to errors package

- pkg/errors/doc.go
- pkg/errors/errors.go
> [easy][errors] Adds better docs

- envsec/go.mod
- envsec/go.sum
- go.work.sum
- pkg/go.mod
- pkg/go.sum
- pkg/runx/impl/registry/extract.go
- tyson/go.mod
- tyson/go.sum
fixes https://github.com/jetify-com/opensource/security/dependabot/30
All community contributions in this pull request are licensed to the project
maintainers under the terms of the
[Apache 2 License](https://www.apache.org/licenses/LICENSE-2.0).
By creating this pull request I represent that I have the right to license the
contributions to the project maintainers under the Apache 2 License as stated in
the
[Community Contribution License](https://github.com/jetify-com/opensource/blob/main/CONTRIBUTING.md#community-contribution-license).
> [deps] Update go deps

- .github/workflows/publish-repos.yml
- aisdk/ai/README.md
- sse/README.md
Start publishing the SSE package from opensource to its own repo.
Update README's to mention Jetify more clearly.
N/A
> Start publishing SSE repo. Mention Jetify in READMEs.

- sse/LICENSE
> Create LICENSE for SSE

- pkg/go.mod
- pkg/osdir/osdir.go
- pkg/osdir/osdir_darwin.go
- pkg/osdir/osdir_linux.go
- pkg/osdir/osdir_test.go
- pkg/osdir/osdir_unix.go
- pkg/osdir/osdir_windows.go
Package osdir provides a cross-platform interface for well-known system and user directories.
The pre-defined DirType package variables use default paths that are specific to the current operating system. The standard XDG environment variables (XDG_CACHE_HOME, XDG_CONFIG_HOME, XDG_DATA_HOME, XDG_STATE_HOME) override these paths when set to a non-empty value, even on macOS and Windows.
Below are the definitions for the default directories on each system.
Linux:
```go
var Cache = DirType{
System: "/var/cache",
User:   "$XDG_CACHE_HOME", UserDefault: "$HOME/.cache",
PrefixHint: "$CACHE_DIRECTORY",
}
var Config = DirType{
System: "/etc",
User:   "$XDG_CONFIG_HOME", UserDefault: "$HOME/.config",
Search: "$XDG_CONFIG_DIRS", SearchDefault: "/etc/xdg",
PrefixHint: "$CONFIGURATION_DIRECTORY",
} …
```
> pkg/osdir: add package for well-known directories

- .github/workflows/api-ts.yaml
- .github/workflows/monorepo-go.yml
- .github/workflows/publish-repos.yml
- .github/workflows/typeid-js.yml
- actions/publish-image/action.yml
- envsec/.github/workflows/tests.yml
> bump devbox-install-action to v0.13.0

- typeid/typeid-go/README.md
> [typeid] Update README to use /v2

- aisdk/ai/go.mod
- aisdk/ai/go.sum
- aisdk/ai/provider/anthropic/codec/decode.go
- aisdk/ai/provider/anthropic/codec/decode_test.go
- aisdk/ai/provider/anthropic/codec/encode_params.go
- aisdk/ai/provider/anthropic/codec/encode_prompt.go
- aisdk/ai/provider/anthropic/codec/encode_prompt_test.go
- aisdk/ai/provider/anthropic/codec/encode_tools.go
- aisdk/ai/provider/anthropic/codec/encode_tools_test.go
- aisdk/ai/provider/anthropic/llm.go
- aisdk/ai/provider/anthropic/llm_test.go
Update AI SDK to use latest version of the Anthropic SDK
Updated tests and ran them
> Update AI SDK to use latest version of the Anthropic SDK
